###### Intro to Numpy 
 Understand the NumPy Python library and its basic functionality.
 Know how to load, manipulate, and analyse data using NumPy.

In [15]:
# Intro to arrays - used for it's efficiency in storage manipulation of numerical data
import numpy as np

In [16]:
# Create an array by passing a nested list
# List is created out of arbitrary numbers
# The list is 3X6 (rows & columns respectively)
scores = np.array([[20,43,54,65,78,78], [89,89,89,89,8,45], [45,90,78,56,43,34]])

In [17]:
# inspect the shape of the array
scores.shape 

(3, 6)

In [18]:
# Creating arrays using built-in methods
# The code should create an array of dimension 3 X 6 populated with ones
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
# The code should create an array of dimension 3 X 6 populated with zeros
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
## The code should create an array of dimension 3 X 6 populated with randaom values

np.random.random((3,6))

array([[0.72351443, 0.0682056 , 0.59718093, 0.63414958, 0.24885774,
        0.66428752],
       [0.2455816 , 0.35604645, 0.68368454, 0.6013724 , 0.22508255,
        0.57807225],
       [0.11806226, 0.51322677, 0.91187237, 0.55827611, 0.229682  ,
        0.4098617 ]])

#### Accessing Numpy Arrays

In [21]:
# We'll use the array created there above from a nested list
# To acccess the whole array

scores

array([[20, 43, 54, 65, 78, 78],
       [89, 89, 89, 89,  8, 45],
       [45, 90, 78, 56, 43, 34]])

In [22]:
#Doing Selection from the top left
scores[0,0]

20

In [24]:
# Accessing the first row
scores[0, :]

array([20, 43, 54, 65, 78, 78])

In [25]:
# Accessing the first column

scores[:, 0]

array([20, 89, 45])

In [27]:
# Accessing first three rows & columns 
scores[0:4, 0:2]

array([[20, 43],
       [89, 89],
       [45, 90]])